spring:
  application:
    name: "oa-telegram"
    parameters:
      telegram:
        chat-id: "${CHAT_ID}"
        bot-id: "${BOT_ID}"
  kafka:
    bootstrap-server: "${KAFKA_ADDRESS:localhost:9092}"
    consumer:
      group-id: "oa-telegram-consumer"
      auto-offset-reset: "earliest"
      enable-auto-commit: true
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        spring.json.trusted.packages: '*'
    topic:
      name: "MessageSent"
    properties:
      spring.json.value.default.type: "dev.jamesbotelho.oatelegram.model.MessageDTO"

server:
  port: "${SEVER_PORT:8081}"